# BigFive Updater - openSUSE Test Container
FROM opensuse/tumbleweed:latest

RUN zypper --non-interactive install \
    curl wget gpg2 ca-certificates \
    && zypper clean -a

WORKDIR /app
COPY guncel install.sh ./
COPY completions/ ./completions/
COPY docs/ ./docs/
COPY lang/ ./lang/

CMD ["bash", "-c", "./guncel --help"]
